"""initial schema

Revision ID: bc62b29b2d0d
Revises:
Create Date: 2026-10-08 21:39:00.849550
"""

from alembic import op
import sqlalchemy as sa


revision = "bc62b29b2d0d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carriers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mc_number", sa.String(length=8), nullable=False),
        sa.Column("dot_number", sa.String(length=20), nullable=True),
        sa.Column("legal_name", sa.String(length=250), nullable=True),
        sa.Column("dba_name", sa.String(length=250), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("allowed_to_operate", sa.String(length=5), nullable=True),
        sa.Column("authority_status", sa.String(length=40), nullable=True),
        sa.Column("safety_rating", sa.String(length=5), nullable=True),
        sa.Column("insurance_on_file", sa.Boolean(), nullable=True),
        sa.Column(
            "bipd_on_file_amount", sa.Numeric(precision=14, scale=2), nullable=True
        ),
        sa.Column(
            "bipd_required_amount", sa.Numeric(precision=14, scale=2), nullable=True
        ),
        sa.Column("out_of_service_date", sa.String(length=30), nullable=True),
        sa.Column("flag", sa.String(length=10), nullable=False),
        sa.Column("flag_reasons", sa.JSON(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_carriers_mc_number"), "carriers", ["mc_number"], unique=True
    )
    op.create_table(
        "communications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("load_id", sa.Integer(), nullable=True),
        sa.Column("carrier_id", sa.Integer(), nullable=True),
        sa.Column("channel", sa.String(length=10), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("from_addr", sa.String(length=320), nullable=True),
        sa.Column("to_addr", sa.String(length=320), nullable=True),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tag", sa.String(length=30), nullable=False),
        sa.Column("attachment_path", sa.String(length=500), nullable=True),
        sa.Column("extracted", sa.JSON(), nullable=True),
        sa.Column("external_id", sa.String(length=300), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id", name="uq_communications_external_id"),
    )
    op.create_index(
        op.f("ix_communications_created_at"),
        "communications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_communications_tag"), "communications", ["tag"], unique=False
    )
    op.create_table(
        "loads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("bol_source", sa.Integer(), nullable=True),
        sa.Column("bol_file_path", sa.String(length=500), nullable=True),
        sa.Column("pickup_location", sa.Text(), nullable=True),
        sa.Column("pickup_city", sa.String(length=100), nullable=True),
        sa.Column("pickup_state", sa.String(length=30), nullable=True),
        sa.Column("pickup_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_location", sa.Text(), nullable=True),
        sa.Column("delivery_city", sa.String(length=100), nullable=True),
        sa.Column("delivery_state", sa.String(length=30), nullable=True),
        sa.Column("delivery_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("weight_lbs", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("equipment_type", sa.String(length=40), nullable=True),
        sa.Column("commodity", sa.String(length=200), nullable=True),
        sa.Column("special_requirements", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("customer_name", sa.String(length=200), nullable=True),
        sa.Column("customer_contact_name", sa.String(length=160), nullable=True),
        sa.Column("customer_email", sa.String(length=320), nullable=True),
        sa.Column("customer_phone", sa.String(length=40), nullable=True),
        sa.Column("customer_rate", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("carrier_rate", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("carrier_id", sa.Integer(), nullable=True),
        sa.Column("driver_name", sa.String(length=160), nullable=True),
        sa.Column("driver_phone", sa.String(length=40), nullable=True),
        sa.Column("driver_email", sa.String(length=320), nullable=True),
        sa.Column("dispatcher_name", sa.String(length=160), nullable=True),
        sa.Column("dispatcher_phone", sa.String(length=40), nullable=True),
        sa.Column("dispatcher_email", sa.String(length=320), nullable=True),
        sa.Column("checkin_offset_minutes", sa.Integer(), nullable=True),
        sa.Column("checkin_channel", sa.String(length=10), nullable=True),
        sa.Column("tracking_token", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("booked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bol_source"],
            ["communications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tracking_token"),
    )
    op.create_index(op.f("ix_loads_reference"), "loads", ["reference"], unique=False)
    op.create_index(op.f("ix_loads_status"), "loads", ["status"], unique=False)
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table("communications") as batch_op:
            batch_op.create_foreign_key(
                "fk_communications_load_id_loads", "loads", ["load_id"], ["id"]
            )
    else:
        op.create_foreign_key(
            "fk_communications_load_id_loads",
            "communications",
            "loads",
            ["load_id"],
            ["id"],
        )
    op.create_table(
        "location_pings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("load_id", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("lng", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("accuracy_m", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["load_id"],
            ["loads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_location_pings_load_id"), "location_pings", ["load_id"], unique=False
    )
    op.create_table(
        "scheduled_checkins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("load_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("scheduled_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("send_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checkin_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checkin_channel", sa.String(length=10), nullable=False),
        sa.Column("driver_contact", sa.String(length=320), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=True),
        sa.Column("reply_received", sa.Boolean(), nullable=False),
        sa.Column("reply_raw_text", sa.Text(), nullable=True),
        sa.Column("reply_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parsed_status", sa.String(length=20), nullable=True),
        sa.Column("parsed_eta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parsed_summary", sa.Text(), nullable=True),
        sa.Column("parse_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("needs_broker_attention", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("alert_raised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alert_dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["load_id"],
            ["loads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_checkins_load_id"),
        "scheduled_checkins",
        ["load_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_checkins_send_at"),
        "scheduled_checkins",
        ["send_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_checkins_state"),
        "scheduled_checkins",
        ["state"],
        unique=False,
    )
    op.create_table(
        "status_updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("load_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("eta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.Column("customer_channel", sa.String(length=10), nullable=True),
        sa.Column("customer_message_subject", sa.String(length=500), nullable=True),
        sa.Column("customer_message_preview", sa.Text(), nullable=True),
        sa.Column("approved_by_broker", sa.Boolean(), nullable=False),
        sa.Column("sent_to_customer", sa.Boolean(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("checkin_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkin_id"],
            ["scheduled_checkins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["load_id"],
            ["loads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_status_updates_load_id"), "status_updates", ["load_id"], unique=False
    )
    op.create_index(
        op.f("ix_status_updates_state"), "status_updates", ["state"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table("communications") as batch_op:
            batch_op.drop_constraint(
                "fk_communications_load_id_loads", type_="foreignkey"
            )
    else:
        op.drop_constraint(
            "fk_communications_load_id_loads", "communications", type_="foreignkey"
        )
    op.drop_index(op.f("ix_status_updates_state"), table_name="status_updates")
    op.drop_index(op.f("ix_status_updates_load_id"), table_name="status_updates")
    op.drop_table("status_updates")
    op.drop_index(op.f("ix_scheduled_checkins_state"), table_name="scheduled_checkins")
    op.drop_index(
        op.f("ix_scheduled_checkins_send_at"), table_name="scheduled_checkins"
    )
    op.drop_index(
        op.f("ix_scheduled_checkins_load_id"), table_name="scheduled_checkins"
    )
    op.drop_table("scheduled_checkins")
    op.drop_index(op.f("ix_location_pings_load_id"), table_name="location_pings")
    op.drop_table("location_pings")
    op.drop_index(op.f("ix_loads_status"), table_name="loads")
    op.drop_index(op.f("ix_loads_reference"), table_name="loads")
    op.drop_table("loads")
    op.drop_index(op.f("ix_communications_tag"), table_name="communications")
    op.drop_index(op.f("ix_communications_created_at"), table_name="communications")
    op.drop_table("communications")
    op.drop_index(op.f("ix_carriers_mc_number"), table_name="carriers")
    op.drop_table("carriers")
    # ### end Alembic commands ###
